### ISSUE TITLE
 00SLiM_mode_finder.py defaults are very slow.

### ISSUE THREAD

**Issue by jmcclena** [maxcurie1996/SLiM#1]
The defaults for `00SLiM_mode_finder.py` (several minutes to run) seem to be much slower than `000GUI_SLiM_mode_finder.py` (few seconds). @maxtcurie do you understand what the difference that causes this? It doesn't seem to be related to `run_mode`

**Comment by jmcclena** [comment]
Actually,  maybe they are similar. `000GUI_SLiM_mode_finder.py` was failing as  another try, except is needed int `tools/Gaussian_fit.py`.

**Comment by maxtcurie** [comment]
I suggest changing the run_mode to 6 (neural net mode) or 2 (normal global mode). Mode 5 is an extensive searching mode.

**Comment by jmcclena** [comment]
Yes, thanks for the recommendations. I think I was just tricked and thought `000GUI_SLiM_mode_finder.py` was faster due to the failure due to the tk issue.
